[profile]
profile_name = "Adrian"
pem_file = "private.pem"

[node]
bootnodes = ["/ip4/137.0.0.1/tcp/5511"]          # List of nodes used at startup to setup communications
interface_mode = "Both" # Allowed values are Both IpV4 & IpV6
port = 5511
