FROM node:18-alpine

WORKDIR /app

COPY ./frontend .
# COPY ./frontend/package.json .

RUN npm install

RUN npm i -g serve

EXPOSE 5174
# RUN npm run dev
CMD [ "npm", "run", "dev" ]


# CMD [ "serve", "-s", "dist" ]
