# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/data/postgres
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  build-backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile-backend.build
    volumes:
      - ./backend/src:/src
      - ./backend/Cargo.toml:/Cargo.toml
    depends_on:
      - postgres

  backend:
    image: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - build-backend
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/rust_sqlx

  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./Dockerfile-frontend.build
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - backend
      - postgres

volumes:
  progresDB:
