FROM rust:1.82

# Install PostgreSQL client library
RUN apt-get update && apt-get install -y libpq-dev

WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .
RUN rm .env

RUN cargo install --path .

EXPOSE 8080
ENTRYPOINT ["backend"]

