# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - progresDB:/data/postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  build:
    image: "backend"
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./src:/src
      - ./Cargo.toml:/Cargo.toml
    depends_on:
      - postgres

  backend:
    image: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - build
    environment:
      - DATABASE_URL=postgresql://postgres:password123@postgres:5432/rust_sqlx
volumes:
  progresDB:
