### add new thread
POST http://localhost:8080/api/threads
Accept: application/json
Content-Type: application/json

{
    "name": "example thread✨"
}

### Get threads
GET http://localhost:8080/api/threads
Accept: application/json


### Delete thread
DELETE http://localhost:8080/api/threads?id=87aa800e-a63f-49f4-81dd-e7e03dee06ef
Accept: application/json
