### add new thread
POST http://localhost:8080/api/thread
Accept: application/json
Content-Type: application/json

{
    "name": "testior"
}

### Get threads
GET http://localhost:8080/api/thread
Accept: application/json
