
### Register new user
POST http://localhost:8080/api/users/register
Accept: application/json
Content-Type: application/json

{
    "name": "krzys",
    "password": "krzysztofpass"
}

### Get users
GET http://localhost:8080/api/users

### Login as user
POST http://localhost:8080/api/users/login
Accept: application/json
Content-Type: application/json

{
    "name": "krzys",
    "password": "krzysztofpass"
}

### Login as user INVALID
POST http://localhost:8080/api/users/login
Accept: application/json
Content-Type: application/json

{
    "name": "krzys",
    "password": "wrongpass"
}


### Login as user INVALID
POST http://localhost:8080/api/users/login
Accept: application/json
Content-Type: application/json
Cookie: 

{
    "name": "krzys",
    "password": "wrongpass"
}
